name: Docker Image CI
on:
  workflow_dispatch:
    inputs:
      push_name:
        description: 'Image_tag NAME'
        required: true
        default: 'v7.7.0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag imocence/bt:${{ github.event.inputs.image_name }}
