name: Docker Image CI
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Image_tag NAME'
        required: true
        default: 'v7.7.0'

jobs:

  build:
    name: Build Images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag imocence/bt:${{ github.event.inputs.tag_name }}
